export { default as Navbar } from './navbar'
export { default as Hero } from './hero'
export { default as Card } from './card'
export { default as Project } from './project'
export { default as Timeline } from './timeline'
